version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: tastebox-redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build: ./TasteBox-Backend
    container_name: tastebox-backend
    ports:
      - "3000:3000"
    env_file:
      - ./TasteBox-Backend/.env
    depends_on:
      - redis
    restart: always

  scheduler:
    build: ./TasteBox-Scheduler
    container_name: tastebox-scheduler
    env_file:
      - ./TasteBox-Scheduler/.env
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: tastebox-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: tastebox-grafana
    ports:
      - "3001:3000"
    env_file:
      - ./TasteBox-Backend/.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    restart: always